# Generated by Django 6.0.1 on 2026-01-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'pl_direccion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año Fiscal')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Plan')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('REFORMADO', 'Reformado')], default='BORRADOR', max_length=20)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan Anual de Contratación (PAC)',
                'verbose_name_plural': 'Planes Anuales (PAC)',
                'db_table': 'pl_pac',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'db_table': 'pl_proceso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('es_movimiento', models.BooleanField(default=True, verbose_name='Es Movimiento')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'pl_unidad',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PACLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpc', models.CharField(max_length=20, verbose_name='Código CPC (SERCOP)')),
                ('tipo_compra', models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio'), ('OBRA', 'Obra'), ('CONSULTORIA', 'Consultoría')], max_length=20)),
                ('detalle', models.TextField(verbose_name='Detalle del producto/servicio')),
                ('cantidad', models.IntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('c1', models.BooleanField(default=False, verbose_name='C1')),
                ('c2', models.BooleanField(default=False, verbose_name='C2')),
                ('c3', models.BooleanField(default=False, verbose_name='C3')),
                ('procedimiento_sugerido', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_original', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Original PDF')),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='planificacion.pac')),
            ],
            options={
                'verbose_name': 'Línea de PAC',
                'verbose_name_plural': 'Líneas de PAC',
                'db_table': 'pl_pac_linea',
            },
        ),
    ]
