# Generated by Django 6.0.1 on 2026-01-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paclinea',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.presupuesto', verbose_name='Partida Presupuestaria'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='planificacion.proceso', verbose_name='Proceso Padre'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='planificacion.direccion', verbose_name='Dirección Padre'),
        ),
    ]
