# Generated by Django 6.0.1 on 2026-01-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'db_table': 'pr_fuente',
            },
        ),
        migrations.CreateModel(
            name='ClasificadorPresupuestario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('codigo_visual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código Visual')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Legal')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('GAS', 'Gasto')], default='GAS', max_length=3, verbose_name='Tipo')),
                ('es_imputable', models.BooleanField(default=False, verbose_name='Es Imputable')),
                ('agrupador', models.BooleanField(default=False, verbose_name='Agrupador')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='presupuestos.clasificadorpresupuestario', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Clasificador Presupuestario',
                'verbose_name_plural': 'Clasificadores Presupuestarios',
                'db_table': 'pr_clasificador',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año')),
                ('partida_concatenada', models.CharField(max_length=100, unique=True, verbose_name='Partida Concatenada')),
                ('asignacion_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Asignación Inicial')),
                ('reformas', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Reformas')),
                ('devengado', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Devengado')),
                ('certificado', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Certificado')),
                ('comprometido', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Comprometido')),
                ('clasificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.clasificadorpresupuestario', verbose_name='Clasificador')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presupuestos.fuentefinanciamiento', verbose_name='Fuente')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificacion.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Registros Presupuestarios',
                'db_table': 'pr_presupuesto',
            },
        ),
    ]
