# Generated by Django 6.0.1 on 2026-02-10 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeNecesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_informe', models.CharField(help_text='Ej: INF-NEC-2026-001', max_length=50, unique=True, verbose_name='Número de Informe')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('objeto_contratacion', models.TextField(help_text='Heredado del PAC, pero editable.', verbose_name='Objeto de Contratación')),
                ('antecedentes', models.TextField(help_text='Describa los antecedentes de la necesidad.', verbose_name='Antecedentes')),
                ('base_legal', models.TextField(default='Reglamento General de la LOSNCP, Art. 65...', help_text='Fundamentación legal.', verbose_name='Base Legal')),
                ('analisis_necesidad', models.TextField(help_text='Justificación de la necesidad.', verbose_name='Análisis de Necesidad')),
                ('conclusion_recomendacion', models.TextField(help_text='Conclusiones y recomendaciones finales.', verbose_name='Conclusión y Recomendación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado Por (Jefe de Área)')),
                ('elaborado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_elaborados', to=settings.AUTH_USER_MODEL, verbose_name='Elaborado Por')),
                ('pac_linea', models.ForeignKey(help_text='Seleccione la línea del PAC para heredar información.', on_delete=django.db.models.deletion.CASCADE, to='planificacion.paclinea', verbose_name='Línea del PAC')),
            ],
            options={
                'verbose_name': 'Informe de Necesidad',
                'verbose_name_plural': 'Informes de Necesidad',
                'db_table': 'cp_informe_necesidad',
            },
        ),
    ]
