"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

# 1. Definir la raiz del proyecto (donde esta manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Inicializar Environ
env = environ.Env()

# 3. Forzar la lectura del archivo .env en la raiz
# Esto busca el archivo C:\Proyectos\riobamba_sge\.env explicitamente
env_file = os.path.join(BASE_DIR, '.env')

if os.path.exists(env_file):
    environ.Env.read_env(env_file)
else:
    print(f"ADVERTENCIA: No se encontró el archivo .env en: {env_file}")

# ... (El resto del archivo sigue igual: SECRET_KEY, DEBUG, etc.)

env = environ.Env()
# reading .env file
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ci)v9^$03*gp@k@^qp=iu^+h1xe@j7+5k!mw&qj8x^26*@ig_&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
    'django_admin_listfilter_dropdown',
    'guardian',
    'apps.core',
    'apps.planificacion',   # 1. Planificación Institucional
    'apps.compras',         # 2. Compras Públicas
    'apps.presupuestos',    # 3. Presupuestos
    'apps.financiero',      # 4. Gestión Financiera
    'apps.tesoreria',       # 5. Tesorería y Pagos
    'apps.contabilidad',    # 6. Contabilidad
    'apps.talento_humano',  # 7. Talento Humano
    'apps.inventario',      # 8. Gestión de Inventario
    'apps.activos',         # 9. Activos Fijos
    'apps.proyectos',       # 10. Gestión de Proyectos
    'apps.permisos',        # 11. Permisos y Trámites
    'apps.agua_potable',    # 12. Agua Potable
    'apps.juridico',        # 13. Gestión Jurídica
    'apps.auditoria',       # 14. Auditoría Interna
    'apps.servicios',       # 15. Servicios Generales
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.auditoria.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(),
    'legacy_activos': {
        'ENGINE': 'config.backends.mysql_legacy',
        'NAME': 'bld_emapar_2023',
        'USER': 'redemapar',
        'PASSWORD': env('LEGACY_DB_PASSWORD', default='CAMBIAR_ESTA_CLAVE'), 
        'HOST': '192.168.2.160',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}

DATABASE_ROUTERS = ['config.db_routers.ActivosRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True
USE_THOUSAND_SEPARATOR = True # Required for intcomma to work properly


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
AUTH_USER_MODEL = 'core.CustomUser'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # default
    'guardian.backends.ObjectPermissionBackend',
)

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# JAZZMIN SETTINGS
JAZZMIN_SETTINGS = {
    "site_title": "SGE Riobamba EP",
    "site_header": "Riobamba EP",
    "site_brand": "Riobamba EP",
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Bienvenido al SGE Riobamba EP",
    "copyright": "Riobamba EP",
    "search_model": "core.CustomUser",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.User"},
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.User"}
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["planificacion", "compras", "presupuestos", "financiero", "tesoreria", "contabilidad", "talento_humano", "inventario", "activos", "proyectos", "permisos", "agua_potable", "juridico", "auditoria", "servicios"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "planificacion": "fas fa-sitemap",
        "compras": "fas fa-shopping-cart",
        "presupuestos": "fas fa-file-invoice-dollar",
        "financiero": "fas fa-hand-holding-usd",
        "tesoreria": "fas fa-cash-register",
        "contabilidad": "fas fa-calculator",
        "talento_humano": "fas fa-users",
        "inventario": "fas fa-boxes",
        "activos": "fas fa-chair",
        "proyectos": "fas fa-project-diagram",
        "permisos": "fas fa-user-clock",
        "agua_potable": "fas fa-faucet",
        "juridico": "fas fa-gavel",
        "auditoria": "fas fa-clipboard-check",
        "servicios": "fas fa-concierge-bell",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cerulean",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# JAZZMIN_SETTINGS = { ... } (Desactivado)
# JAZZMIN_UI_TWEAKS = { ... } (Desactivado)

DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000 # Increased for large PAC inlines

