# Generated by Django 6.0.1 on 2026-01-15 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificadorPresupuestario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('GAS', 'Gasto')], default='GAS', max_length=3, verbose_name='Tipo')),
                ('agrupador', models.BooleanField(default=False, verbose_name='Agrupador')),
            ],
            options={
                'verbose_name': 'Clasificador Presupuestario',
                'verbose_name_plural': 'Clasificadores Presupuestarios',
                'db_table': 'fi_clasificador',
            },
        ),
        migrations.CreateModel(
            name='EstructuraProgramatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Estructura Programática',
                'verbose_name_plural': 'Estructuras Programáticas',
                'db_table': 'fi_estructura_programatica',
            },
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'db_table': 'fi_fuente',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año')),
                ('partida_concatenada', models.CharField(max_length=100, unique=True, verbose_name='Partida Concatenada')),
                ('asignacion_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Asignación Inicial')),
                ('reformas', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Reformas')),
                ('devengado', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Devengado')),
                ('clasificador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.clasificadorpresupuestario', verbose_name='Clasificador')),
                ('estructura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiero.estructuraprogramatica', verbose_name='Estructura')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiero.fuentefinanciamiento', verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Registros Presupuestarios',
                'db_table': 'fi_presupuesto',
            },
        ),
    ]
