# Generated by Django 6.0.1 on 2026-01-15 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estructuraprogramatica',
            options={'ordering': ['codigo'], 'verbose_name': 'Estructura Programática', 'verbose_name_plural': 'Estructuras Programáticas'},
        ),
        migrations.AddField(
            model_name='estructuraprogramatica',
            name='es_movimiento',
            field=models.BooleanField(default=True, verbose_name='Es Movimiento'),
        ),
        migrations.AddField(
            model_name='estructuraprogramatica',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='financiero.estructuraprogramatica', verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='estructuraprogramatica',
            name='codigo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Código'),
        ),
    ]
