# Generated by Django 6.0.1 on 2026-01-15 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0002_alter_estructuraprogramatica_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'db_table': 'fi_proceso',
                'ordering': ['codigo'],
            },
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='estructura',
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='financiero.proceso', verbose_name='Proceso Padre')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'fi_direccion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('es_movimiento', models.BooleanField(default=True, verbose_name='Es Movimiento')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='financiero.direccion', verbose_name='Dirección Padre')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'fi_unidad',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiero.unidad', verbose_name='Unidad'),
        ),
        migrations.DeleteModel(
            name='EstructuraProgramatica',
        ),
    ]
