# Generated by Django 6.0.1 on 2026-01-15 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0003_proceso_remove_presupuesto_estructura_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificadorpresupuestario',
            options={'ordering': ['codigo'], 'verbose_name': 'Clasificador Presupuestario', 'verbose_name_plural': 'Clasificadores Presupuestarios'},
        ),
        migrations.AddField(
            model_name='clasificadorpresupuestario',
            name='codigo_formateado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código (Visual)'),
        ),
        migrations.AddField(
            model_name='clasificadorpresupuestario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Legal'),
        ),
        migrations.AddField(
            model_name='clasificadorpresupuestario',
            name='es_imputable',
            field=models.BooleanField(default=False, verbose_name='Es Imputable'),
        ),
        migrations.AddField(
            model_name='clasificadorpresupuestario',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='clasificadorpresupuestario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='financiero.clasificadorpresupuestario', verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='clasificadorpresupuestario',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código (Limpio)'),
        ),
        migrations.AlterField(
            model_name='clasificadorpresupuestario',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
