# Generated by Django 6.0.1 on 2026-01-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0004_alter_clasificadorpresupuestario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificadorpresupuestario',
            name='codigo_formateado',
        ),
        migrations.AlterField(
            model_name='clasificadorpresupuestario',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
