# Generated by Django 6.0.1 on 2026-01-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0005_remove_clasificadorpresupuestario_codigo_formateado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificadorpresupuestario',
            name='codigo_visual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código Visual'),
        ),
    ]
