# Generated by Django 6.0.1 on 2026-01-18 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0006_clasificadorpresupuestario_codigo_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='certificado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Certificado'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='comprometido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Comprometido'),
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('SOL', 'Solicitado'), ('APR', 'Aprobado'), ('CAN', 'Cancelado'), ('LIQ', 'Liquidado')], default='BOR', max_length=3, verbose_name='Estado')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Monto Total')),
                ('pdf_respaldo', models.FileField(blank=True, null=True, upload_to='certificaciones/', verbose_name='PDF Respaldo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.unidad', verbose_name='Unidad Solicitante')),
            ],
            options={
                'verbose_name': 'Certificación Presupuestaria',
                'verbose_name_plural': 'Certificaciones Presupuestarias',
                'db_table': 'fi_certificacion',
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='CertificacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='financiero.certificacion', verbose_name='Certificación')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.presupuesto', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Detalle de Certificación',
                'verbose_name_plural': 'Detalles de Certificación',
                'db_table': 'fi_certificacion_detalle',
            },
        ),
    ]
