# Generated by Django 6.0.1 on 2026-01-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0007_presupuesto_certificado_presupuesto_comprometido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('APR', 'Aprobado'), ('REF', 'Reformado')], default='BOR', max_length=3, verbose_name='Estado')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación')),
            ],
            options={
                'verbose_name': 'Plan Anual de Contratación (PAC)',
                'verbose_name_plural': 'Planes Anuales de Contratación',
                'db_table': 'fi_pac',
            },
        ),
        migrations.CreateModel(
            name='PACLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpc', models.CharField(max_length=9, verbose_name='Código CPC')),
                ('tipo_compra', models.CharField(choices=[('Bie', 'Bien'), ('Ser', 'Servicio'), ('Obr', 'Obra'), ('Con', 'Consultoría')], max_length=3, verbose_name='Tipo de Compra')),
                ('detalle', models.TextField(verbose_name='Detalle del Objeto')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Costo Unitario')),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name='Monto Total')),
                ('cuatrimestre', models.IntegerField(choices=[(1, 'Cuatrimestre 1'), (2, 'Cuatrimestre 2'), (3, 'Cuatrimestre 3')], verbose_name='Cuatrimestre')),
                ('procedimiento_sugerido', models.CharField(choices=[('IC', 'Infima Cuantía'), ('SI', 'Subasta Inversa'), ('LI', 'Licitación'), ('CE', 'Catálogo Electrónico')], max_length=50, verbose_name='Procedimiento Sugerido')),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='financiero.pac', verbose_name='PAC')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiero.presupuesto', verbose_name='Partida Presupuestaria')),
            ],
            options={
                'verbose_name': 'Línea del PAC',
                'verbose_name_plural': 'Líneas del PAC',
                'db_table': 'fi_pac_linea',
            },
        ),
    ]
