# Generated by Django 6.0.1 on 2026-01-18 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0008_pac_paclinea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pac',
            options={'verbose_name': 'Plan Anual de Contratación (PAC)', 'verbose_name_plural': 'Planes Anuales (PAC)'},
        ),
        migrations.AlterModelOptions(
            name='paclinea',
            options={},
        ),
        migrations.AddField(
            model_name='pac',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pac',
            name='anio',
            field=models.IntegerField(default=2026, verbose_name='Año Fiscal'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción del Plan'),
        ),
        migrations.AlterField(
            model_name='pac',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('REFORMADO', 'Reformado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='pac',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='cpc',
            field=models.CharField(max_length=20, verbose_name='Código CPC (SERCOP)'),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='cuatrimestre',
            field=models.CharField(choices=[('1', 'Primer Cuatrimestre (Ene-Abr)'), ('2', 'Segundo Cuatrimestre (May-Ago)'), ('3', 'Tercer Cuatrimestre (Sep-Dic)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='detalle',
            field=models.TextField(verbose_name='Detalle del producto/servicio'),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='financiero.pac'),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='procedimiento_sugerido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paclinea',
            name='tipo_compra',
            field=models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio'), ('OBRA', 'Obra'), ('CONSULTORIA', 'Consultoría')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='pac',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paclinea',
            table=None,
        ),
    ]
