# Generated by Django 6.0.1 on 2026-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0009_alter_pac_options_alter_paclinea_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paclinea',
            name='codigo_original',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Original PDF'),
        ),
    ]
