# Generated by Django 6.0.1 on 2026-01-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0010_paclinea_codigo_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paclinea',
            name='cuatrimestre',
        ),
        migrations.AddField(
            model_name='paclinea',
            name='c1',
            field=models.BooleanField(default=False, verbose_name='C1'),
        ),
        migrations.AddField(
            model_name='paclinea',
            name='c2',
            field=models.BooleanField(default=False, verbose_name='C2'),
        ),
        migrations.AddField(
            model_name='paclinea',
            name='c3',
            field=models.BooleanField(default=False, verbose_name='C3'),
        ),
    ]
