# Generated by Django 6.0.1 on 2026-01-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0011_remove_paclinea_cuatrimestre_paclinea_c1_paclinea_c2_and_more'),
        ('planificacion', '0002_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='clasificador',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='paclinea',
            name='pac',
        ),
        migrations.RemoveField(
            model_name='paclinea',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='certificaciondetalle',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.presupuesto', verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planificacion.unidad', verbose_name='Unidad Solicitante'),
        ),
        migrations.DeleteModel(
            name='ClasificadorPresupuestario',
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='FuenteFinanciamiento',
        ),
        migrations.DeleteModel(
            name='PAC',
        ),
        migrations.DeleteModel(
            name='PACLinea',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
