# Generated by Django 6.0.1 on 2026-01-19 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Edición'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('VIEW', 'Vista'), ('OTHER', 'Otro')], max_length=20, verbose_name='Acción')),
                ('ruta', models.CharField(max_length=255, verbose_name='Ruta / URL')),
                ('metodo', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle_cambios', models.JSONField(blank=True, null=True, verbose_name='Detalle de Cambios (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('duracion', models.FloatField(help_text='Duración de la operación en segundos', verbose_name='Duración (s)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'au_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
